#!/usr/bin/env node

import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { buildReviewPacket } from "./content_language_review.mjs";
import { AWKWARD_FOOTBALL_COPY_PATTERNS } from "./generate_content_article.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedDirectory = path.join(projectRoot, "src", "content", "generated");

function extractNumbers(text) {
  return [...text.matchAll(/\d+(?:[.,]\d+)?/g)].map((match) => Number(match[0].replace(",", ".")));
}

function numbersMatch(left, right) {
  return Math.abs(Number(left) - Number(right)) < 0.005;
}

function claims(article) {
  return [
    { text: article.editorial.headline, evidenceIds: article.editorial.headlineEvidenceIds },
    { text: article.editorial.dek, evidenceIds: article.editorial.dekEvidenceIds },
    ...article.editorial.sections.flatMap((section) => section.paragraphs),
    ...article.editorial.takeaways,
    { text: article.editorial.conclusion, evidenceIds: article.editorial.conclusionEvidenceIds },
  ];
}

function decisiveWindowScorerNames(mechanismContext) {
  const decisiveWindow = mechanismContext?.decisiveWindow;
  if (!decisiveWindow) return [];
  const dominantShooters = decisiveWindow.away?.goals > decisiveWindow.home?.goals
    ? decisiveWindow.awayShooters
    : decisiveWindow.home?.goals > decisiveWindow.away?.goals
      ? decisiveWindow.homeShooters
      : [...(decisiveWindow.homeShooters ?? []), ...(decisiveWindow.awayShooters ?? [])];
  return [...(dominantShooters ?? [])]
    .filter((shooter) => shooter.goals > 0 && shooter.playerNameHe)
    .sort((left, right) => right.goals - left.goals || right.expectedGoals - left.expectedGoals)
    .slice(0, 2)
    .map((shooter) => shooter.playerNameHe);
}

function validateArticle(article, filename) {
  const failures = [];
  const fail = (message) => failures.push(`${filename}: ${message}`);
  if (article.schemaVersion !== 1) fail("unsupported schemaVersion");
  if (article.language !== "he") fail("content must be Hebrew-only");
  if (article.status !== "published") fail("generated article is not published");
  if (article.generation?.mode !== "codex_skill") {
    fail("published article did not run the Codex skill workflow");
  }
  if (article.generation?.pipelineVersion !== "match-review-v21") fail("published article was not generated by the current pipeline version");
  const roleIds = Object.values(article.authorship ?? {});
  if (roleIds.length !== 4 || roleIds.some((id) => typeof id !== "string" || !id) || new Set(roleIds).size !== 4) {
    fail("analyst, writer, editor, and reviewer roles are not distinct");
  }
  if (article.factCheck?.status !== "passed") fail("fact-check status is not passed");
  if (article.factCheck?.checks?.some((check) => check.status !== "passed")) fail("one or more stored fact checks failed");
  if (article.editorialReview?.status !== "passed" || !Object.values(article.editorialReview?.checks ?? {}).every(Boolean)) {
    fail("Hebrew editorial review is missing or failed");
  }
  if (article.editorialReview?.mode !== "codex_skill_editor") {
    fail("published article did not run the Codex skill editorial pass");
  }
  if (
    article.qualityReview?.mode !== "codex_skill_quality_gate"
    || article.qualityReview?.status !== "passed"
    || !Object.values(article.qualityReview?.checks ?? {}).every(Boolean)
    || article.qualityReview?.issues?.length !== 0
  ) {
    fail("published article did not pass the Codex skill quality gate");
  }
  const packet = buildReviewPacket({
    schemaVersion: 2,
    draftEditorial: null,
    editorial: article.editorial,
    analysisPlan: article.analysisPlan,
  });
  if (article.editorialReview?.finalHash !== packet.finalHash) fail("editorial review hash does not match final copy");
  if (article.qualityReview?.reviewedHash !== packet.finalHash) fail("blind review hash does not match final copy");
  if (article.qualityReview?.numberlessHash !== packet.numberlessHash) fail("blind review hash does not match numberless copy");
  const expectedSentences = new Map(packet.sentences.map((entry) => [entry.location, entry.text]));
  for (const [label, reviews] of [
    ["editorial", article.editorialReview?.sentenceReviews],
    ["blind", article.qualityReview?.sentenceReviews],
  ]) {
    if (!Array.isArray(reviews) || reviews.length !== expectedSentences.size) {
      fail(`${label} language review does not cover every visible sentence`);
      continue;
    }
    const covered = new Set();
    for (const review of reviews) {
      if (covered.has(review.location)) fail(`${label} language review contains a duplicate sentence location`);
      covered.add(review.location);
      if (expectedSentences.get(review.location) !== review.text || review.verdict !== "passed") {
        fail(`${label} language review does not approve the exact final sentence at ${review.location}`);
      }
    }
  }
  if (
    article.qualityReview?.numberlessReview?.status !== "passed"
    || article.qualityReview?.numberlessReview?.articleStillCoherent !== true
    || article.qualityReview?.numberlessReview?.issues?.length !== 0
  ) {
    fail("article did not pass the numberless-story review");
  }
  if (!article.historicalContext) fail("historical comparison context is missing");
  if (!article.historicalAuditContext) fail("historical audit context is missing");
  if (!article.gameStateContext) fail("game-state context is missing");
  if (!article.mechanismContext) fail("mechanism context is missing");
  if (!article.analysisPlan) fail("analysis plan is missing");
  if (!article.tags?.some((tag) => tag.id === "topic:match-summary")) fail("match-summary tag is missing");
  if ((article.tags ?? []).filter((tag) => tag.kind === "team").length !== 2) fail("article must include both team tags");
  if (!(article.tags ?? []).some((tag) => tag.kind === "player")) fail("article must include at least one player tag");

  const { home, away } = article.teams;
  const homeShots = article.shots.filter((shot) => shot.teamId === home.teamId);
  const awayShots = article.shots.filter((shot) => shot.teamId === away.teamId);
  if (homeShots.length !== home.stats.team_total_shots) fail("home shot total does not match the shot map");
  if (awayShots.length !== away.stats.team_total_shots) fail("away shot total does not match the shot map");
  if (homeShots.filter((shot) => shot.outcome === "Goal").length !== home.score) fail("home goals do not match shot events");
  if (awayShots.filter((shot) => shot.outcome === "Goal").length !== away.score) fail("away goals do not match shot events");

  const historicalMatches = article.historicalContext
    ? [...article.historicalContext.teams.home.matches, ...article.historicalContext.teams.away.matches]
    : [];
  if (historicalMatches.some((match) => Date.parse(match.scheduledAt) >= Date.parse(article.match.scheduledAt))) {
    fail("historical comparison contains a match that did not precede the article match");
  }

  const evidenceById = new Map(article.evidence.map((item) => [item.id, item]));
  for (const id of ["team.volume", "team.quality", "team.progression", "matchup.midfield", "matchup.home_attack_away_defense", "matchup.away_attack", "flow.shot_windows", "flow.game_state_context", "mechanism.chance_creation", "mechanism.decisive_window", "heatmap.spatial_profile", "history.audit"]) {
    if (!evidenceById.get(id)?.context) fail(`structured evidence context is missing for ${id}`);
  }
  const plannedInsightIds = new Set((article.analysisPlan?.rankedInsights ?? []).map((insight) => insight.id));
  const sectionInsightIds = article.editorial.sections.flatMap((section) => section.insightIds ?? []);
  if (sectionInsightIds.some((id) => !plannedInsightIds.has(id))) fail("article section references an unplanned insight");
  const primaryInsightIds = (article.analysisPlan?.rankedInsights ?? []).filter((insight) => insight.importance === "primary").map((insight) => insight.id);
  if (primaryInsightIds.some((id) => !sectionInsightIds.includes(id))) fail("a primary insight is missing from the article sections");
  const graphics = article.analysisPlan?.graphics ?? [];
  if (graphics.length < 2 || graphics.length > 4) fail("analysis plan must select 2–4 graphics");
  if (new Set(graphics.map((graphic) => graphic.type)).size !== graphics.length) fail("graphic types must be distinct");
  const plannedInsightById = new Map((article.analysisPlan?.rankedInsights ?? []).map((insight) => [insight.id, insight]));
  for (const graphic of graphics) {
    if (!plannedInsightIds.has(graphic.placementInsightId)) fail(`graphic references an unplanned insight ${graphic.placementInsightId}`);
    if (graphic.evidenceIds.some((id) => !evidenceById.has(id))) fail(`graphic references unknown evidence: ${graphic.titleHe}`);
    if (!graphic.evidenceIds.some((id) => plannedInsightById.get(graphic.placementInsightId)?.evidenceIds.includes(id))) fail(`graphic does not share evidence with its insight: ${graphic.titleHe}`);
    if (graphic.type === "player_focus" && !article.players.some((player) => player.playerId === graphic.focusPlayerId)) fail("player graphic references an unknown player");
    if (graphic.type === "team_history" && (!graphic.metricCodes.length || graphic.metricCodes.some((code) => !article.historicalContext.teams.home.metrics[code] && !article.historicalContext.teams.away.metrics[code]))) fail("history graphic references an unavailable metric");
    if (extractNumbers(`${graphic.titleHe} ${graphic.subtitleHe}`).length) fail("graphic titles and subtitles must not contain numbers");
  }
  if (article.gameStateContext?.rawShotTotalsNeedGameStateContext) {
    const earlyGameStateSection = article.editorial.sections.slice(0, 2).some((section) => (
      section.insightIds?.includes("game_state_distortion")
      && section.paragraphs.some((paragraph) => paragraph.evidenceIds?.includes("flow.game_state_context"))
    ));
    if (!earlyGameStateSection) fail("misleading cumulative totals are not contextualized in the opening two sections");
  }
  const requiredMechanismInsightIds = (article.insightCandidates ?? [])
    .filter((candidate) => ["chance_creation_mechanism", "decisive_window_mechanism"].includes(candidate.id) && candidate.score >= 75)
    .map((candidate) => candidate.id);
  for (const insightId of requiredMechanismInsightIds) {
    const mechanismEvidenceId = insightId === "chance_creation_mechanism" ? "mechanism.chance_creation" : "mechanism.decisive_window";
    const plannedInsight = (article.analysisPlan?.rankedInsights ?? []).find((insight) => insight.id === insightId);
    if (!plannedInsight?.evidenceIds?.includes(mechanismEvidenceId)) fail(`required mechanism insight is missing: ${insightId}`);
    const usedInSection = article.editorial.sections.some((section) => section.insightIds?.includes(insightId)
      && section.paragraphs.some((paragraph) => paragraph.evidenceIds?.includes(mechanismEvidenceId)));
    if (!usedInSection) fail(`article does not explain the selected mechanism: ${insightId}`);
  }
  if (requiredMechanismInsightIds.includes("decisive_window_mechanism")) {
    const decisiveCopy = article.editorial.sections
      .filter((section) => section.insightIds?.includes("decisive_window_mechanism"))
      .flatMap((section) => section.paragraphs.map((paragraph) => paragraph.text))
      .join(" ");
    const missingScorers = decisiveWindowScorerNames(article.mechanismContext).filter((name) => !decisiveCopy.includes(name));
    if (missingScorers.length) fail(`decisive-window scorers are missing from the article body: ${missingScorers.join(", ")}`);
  }
  if (requiredMechanismInsightIds.includes("chance_creation_mechanism")) {
    const chanceCopy = article.editorial.sections
      .filter((section) => section.insightIds?.includes("chance_creation_mechanism"))
      .flatMap((section) => section.paragraphs.map((paragraph) => paragraph.text))
      .join(" ");
    const explainsShotLocation = /מרכז\s+הרחבה|בתוך\s+הרחבה|מהרחבה|אג(?:ף|פים)|כנפ(?:יים|ף)|חצי[־-]ה?מרחב/.test(chanceCopy);
    const explainsRoleDivision = /שחקני\s+(?:ההתקפה|ההגנה|הקישור)|הקו\s+הקדמי|החלוצים|המגנים|קו\s+ההגנה|הקשרים|חוליית\s+(?:ההתקפה|ההגנה|הקישור)/.test(chanceCopy);
    if (!explainsShotLocation || !explainsRoleDivision) fail("chance-creation section does not connect shot location with role division");
  }
  if (!article.analysisPlan?.historicalAudit?.teamSignalsReviewed
    || !article.analysisPlan?.historicalAudit?.playerSignalsReviewed
    || !article.analysisPlan?.historicalAudit?.evidenceIds?.includes("history.audit")) {
    fail("analysis plan did not complete the historical audit");
  }
  const claimEvidenceIds = new Set(claims(article).flatMap((claim) => claim.evidenceIds ?? []));
  const usesHistory = [...claimEvidenceIds].some((id) => id.startsWith("history.team.") || id.startsWith("history.player."));
  if (article.analysisPlan?.historicalAudit?.decision === "use" ? !usesHistory : usesHistory) {
    fail("article history usage does not match the historical audit decision");
  }
  const historicalPlayerByEvidenceId = new Map((article.historicalContext?.players ?? []).map((player) => [
    `history.player.${player.playerId}`,
    player,
  ]));
  for (const claim of claims(article)) {
    if (!claim.evidenceIds?.length) fail(`claim has no evidence: ${claim.text}`);
    const allowed = claim.evidenceIds.flatMap((id) => evidenceById.get(id)?.values ?? []);
    for (const id of claim.evidenceIds) if (!evidenceById.has(id)) fail(`unknown evidence ID ${id}`);
    for (const id of claim.evidenceIds) {
      if (id.startsWith("history.player.") && !(historicalPlayerByEvidenceId.get(id)?.notableChanges?.length > 0)) {
        fail(`weak historical player comparison: ${claim.text}`);
      }
    }
    for (const value of extractNumbers(claim.text)) {
      if (!allowed.some((candidate) => numbersMatch(candidate, value))) fail(`unsupported number ${value}: ${claim.text}`);
    }
  }
  const paragraphNumberCounts = article.editorial.sections.flatMap((section) => section.paragraphs.map((paragraph) => extractNumbers(paragraph.text).length));
  if (paragraphNumberCounts.some((count) => count > 6)) fail(`a paragraph contains too many numbers: ${paragraphNumberCounts.join(", ")}`);
  if (paragraphNumberCounts.reduce((sum, count) => sum + count, 0) / Math.max(paragraphNumberCounts.length, 1) > 4) fail("the article has excessive average numeric density");
  const bodyNumbers = article.editorial.sections.flatMap((section) => section.paragraphs.flatMap((paragraph) => extractNumbers(paragraph.text)));
  if (article.editorial.takeaways.some((takeaway) => extractNumbers(takeaway.text).some((value) => !bodyNumbers.some((candidate) => numbersMatch(candidate, value))))) fail("a takeaway introduces a number that was not explained in the article body");
  const bodyCopy = article.editorial.sections.flatMap((section) => section.paragraphs.map((paragraph) => paragraph.text)).join(" ");
  const summaryCopy = `${article.editorial.conclusion} ${article.editorial.takeaways.map((takeaway) => takeaway.text).join(" ")}`;
  const ungroundedSummaryPlayers = article.players
    .filter((player) => player.nameHe && summaryCopy.includes(player.nameHe) && !bodyCopy.includes(player.nameHe))
    .map((player) => player.nameHe);
  if (ungroundedSummaryPlayers.length) fail(`players appear first in the summary: ${ungroundedSummaryPlayers.join(", ")}`);
  const summaryRolePatterns = [
    /שחקני\s+ההתקפה|הקו\s+הקדמי|החלוצים|חוליית\s+ההתקפה/,
    /שחקני\s+ההגנה|המגנים|קו\s+ההגנה|חוליית\s+ההגנה/,
    /שחקני\s+הקישור|הקשרים|חוליית\s+הקישור/,
  ];
  if (summaryRolePatterns.some((pattern) => pattern.test(summaryCopy) && !pattern.test(bodyCopy))) {
    fail("a unit-level claim appears first in the summary");
  }
  if (/(?:פרופיל\s+מרחבי|מפת\s+חום)/.test(summaryCopy) && !/(?:פרופיל\s+מרחבי|מפת\s+חום)/.test(bodyCopy)) {
    fail("spatial evidence appears first in the summary");
  }
  const undefinedQualityLabels = article.editorial.sections.flatMap((section) => section.paragraphs).filter((paragraph) => (
    /(?:מצב(?:ים)?|בעיט(?:ה|ות))\s+(?:ב)?איכות\s+גבוהה/.test(paragraph.text)
    && !/0[.,]2(?:0)?\s*xG/.test(paragraph.text)
  ));
  if (undefinedQualityLabels.length) fail("high-quality chance label is missing the 0.20 xG definition");
  const editorialCopy = claims(article).map((claim) => claim.text).join(" ");
  for (const pattern of AWKWARD_FOOTBALL_COPY_PATTERNS) {
    if (pattern.test(editorialCopy)) fail(`editorial copy contains a blocked phrasing pattern: ${pattern}`);
  }
  return failures;
}

async function main() {
  const files = (await readdir(generatedDirectory)).filter((file) => file.endsWith(".json"));
  if (!files.length) throw new Error("No generated content articles were found.");
  const failures = [];
  for (const file of files) {
    const article = JSON.parse(await readFile(path.join(generatedDirectory, file), "utf8"));
    failures.push(...validateArticle(article, file));
  }
  if (failures.length) throw new Error(`Content validation failed:\n${failures.map((failure) => `- ${failure}`).join("\n")}`);
  console.log(`${files.length} article(s) passed structural, evidence, score, and numeric-claim validation.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
