#!/usr/bin/env node

import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedDirectory = path.join(projectRoot, "src", "content", "generated");

function extractNumbers(text) {
  return [...text.matchAll(/\d+(?:[.,]\d+)?/g)].map((match) => Number(match[0].replace(",", ".")));
}

function numbersMatch(left, right) {
  return Math.abs(Number(left) - Number(right)) < 0.005;
}

function claims(article) {
  return [
    { text: article.editorial.headline, evidenceIds: article.editorial.headlineEvidenceIds },
    { text: article.editorial.dek, evidenceIds: article.editorial.dekEvidenceIds },
    ...article.editorial.sections.flatMap((section) => section.paragraphs),
    ...article.editorial.takeaways,
    { text: article.editorial.conclusion, evidenceIds: article.editorial.conclusionEvidenceIds },
  ];
}

function validateArticle(article, filename) {
  const failures = [];
  const fail = (message) => failures.push(`${filename}: ${message}`);
  if (article.schemaVersion !== 1) fail("unsupported schemaVersion");
  if (article.language !== "he") fail("content must be Hebrew-only");
  if (article.status !== "published") fail("generated article is not published");
  if (article.generation?.mode !== "openai_writer_editor_and_qa") {
    fail("published article did not run the AI writer-editor-and-QA pipeline");
  }
  if (article.generation?.pipelineVersion !== "match-review-v9") fail("published article was not generated by the current pipeline version");
  if (article.factCheck?.status !== "passed") fail("fact-check status is not passed");
  if (article.factCheck?.checks?.some((check) => check.status !== "passed")) fail("one or more stored fact checks failed");
  if (article.editorialReview?.status !== "passed" || !Object.values(article.editorialReview?.checks ?? {}).every(Boolean)) {
    fail("Hebrew editorial review is missing or failed");
  }
  if (article.editorialReview?.mode !== "openai_second_pass_editor") {
    fail("published article did not run the independent AI editorial pass");
  }
  if (
    article.qualityReview?.mode !== "openai_independent_quality_gate"
    || article.qualityReview?.status !== "passed"
    || !Object.values(article.qualityReview?.checks ?? {}).every(Boolean)
    || article.qualityReview?.issues?.length !== 0
  ) {
    fail("published article did not pass the independent Hebrew quality gate");
  }
  if (!article.historicalContext) fail("historical comparison context is missing");
  if (!article.tags?.some((tag) => tag.id === "topic:match-summary")) fail("match-summary tag is missing");
  if ((article.tags ?? []).filter((tag) => tag.kind === "team").length !== 2) fail("article must include both team tags");
  if (!(article.tags ?? []).some((tag) => tag.kind === "player")) fail("article must include at least one player tag");

  const { home, away } = article.teams;
  const homeShots = article.shots.filter((shot) => shot.teamId === home.teamId);
  const awayShots = article.shots.filter((shot) => shot.teamId === away.teamId);
  if (homeShots.length !== home.stats.team_total_shots) fail("home shot total does not match the shot map");
  if (awayShots.length !== away.stats.team_total_shots) fail("away shot total does not match the shot map");
  if (homeShots.filter((shot) => shot.outcome === "Goal").length !== home.score) fail("home goals do not match shot events");
  if (awayShots.filter((shot) => shot.outcome === "Goal").length !== away.score) fail("away goals do not match shot events");

  const historicalMatches = article.historicalContext
    ? [...article.historicalContext.teams.home.matches, ...article.historicalContext.teams.away.matches]
    : [];
  if (historicalMatches.some((match) => Date.parse(match.scheduledAt) >= Date.parse(article.match.scheduledAt))) {
    fail("historical comparison contains a match that did not precede the article match");
  }

  const evidenceById = new Map(article.evidence.map((item) => [item.id, item]));
  for (const id of ["team.volume", "team.quality", "team.progression", "matchup.midfield", "matchup.home_attack_away_defense", "matchup.away_attack", "flow.shot_windows", "heatmap.spatial_profile"]) {
    if (!evidenceById.get(id)?.context) fail(`structured evidence context is missing for ${id}`);
  }
  const usedEvidenceIds = new Set(claims(article).flatMap((claim) => claim.evidenceIds ?? []));
  if (!usedEvidenceIds.has("heatmap.spatial_profile")) fail("article has no grounded spatial insight");
  if (![...usedEvidenceIds].some((id) => id.startsWith("matchup."))) fail("article has no grounded unit-matchup insight");
  const historicalPlayerByEvidenceId = new Map((article.historicalContext?.players ?? []).map((player) => [
    `history.player.${player.playerId}`,
    player,
  ]));
  for (const claim of claims(article)) {
    if (!claim.evidenceIds?.length) fail(`claim has no evidence: ${claim.text}`);
    const allowed = claim.evidenceIds.flatMap((id) => evidenceById.get(id)?.values ?? []);
    for (const id of claim.evidenceIds) if (!evidenceById.has(id)) fail(`unknown evidence ID ${id}`);
    for (const id of claim.evidenceIds) {
      if (id.startsWith("history.player.") && !(historicalPlayerByEvidenceId.get(id)?.notableChanges?.length > 0)) {
        fail(`weak historical player comparison: ${claim.text}`);
      }
    }
    for (const value of extractNumbers(claim.text)) {
      if (!allowed.some((candidate) => numbersMatch(candidate, value))) fail(`unsupported number ${value}: ${claim.text}`);
    }
  }
  const editorialCopy = claims(article).map((claim) => claim.text).join(" ");
  for (const pattern of [/הפך מחריגה לסיפור/, /ההיסטוריה הקצרה שלהם/, /המספרים מספרים/, /צבר(?:ה|ו)? את רוב האיום/, /xG\s*;/, /השערים פונו/, /כיתרה\s+\d/, /המצביה/, /ריבוי דו[־-]קרקעי/, /גלים של איומים/, /שימור איזון בנפח/]) {
    if (pattern.test(editorialCopy)) fail(`editorial copy contains a blocked phrasing pattern: ${pattern}`);
  }
  return failures;
}

async function main() {
  const files = (await readdir(generatedDirectory)).filter((file) => file.endsWith(".json"));
  if (!files.length) throw new Error("No generated content articles were found.");
  const failures = [];
  for (const file of files) {
    const article = JSON.parse(await readFile(path.join(generatedDirectory, file), "utf8"));
    failures.push(...validateArticle(article, file));
  }
  if (failures.length) throw new Error(`Content validation failed:\n${failures.map((failure) => `- ${failure}`).join("\n")}`);
  console.log(`${files.length} article(s) passed structural, evidence, score, and numeric-claim validation.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
